name: Build and Compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up build environment
        run: sudo apt update && sudo apt install -y build-essential automake

      - name: Configure and Build
        run: |
          autoreconf --install
          ./configure
          make
      
      - name: Create tarball
        run: make dist
      
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: my_program_tarball
          path: ./*.tar.gz

