name: Build and Push Multi-Architecture Image

on:
  push:
    branches: ["branchHTTPserver"]
  pull_request:
    branches: ["branchHTTPserver"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform=linux/${{ matrix.architecture }} \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/http_server:${{ matrix.architecture }} . || exit 1

      - name: Verify image exists
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/http_server:${{ matrix.architecture }} || echo "Image not found for ${{ matrix.architecture }}"

      - name: Create and push multi-architecture manifest
        if: always()
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/http_server:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/http_server:amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/http_server:arm64 || exit 1
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/http_server:latest

