name: Build and Compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up C++ environment
        run: sudo apt update && sudo apt install -y build-essential
      - name: Build with Makefile
        run: make
