on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autotools-dev autoconf curl

      - name: Build the project
        run: |
          autoreconf -i
          ./configure
          make

      - name: Start HTTP server
        run: ./HTTP_Server &

      - name: Test HTTP server
        run: curl -X GET http://localhost:8081/compute
