name: build

on:
  push:
    branches:
      - branchHTTPservMutli

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: qurtis99/http-server:latest-${{ matrix.arch }}
        platforms: linux/${{ matrix.arch }}
        cache-from: type=registry,ref=qurtis99/http-server:cache
        cache-to: type=inline

    - name: Create and push multi-architecture manifest
      run: |
        docker manifest create qurtis99/http-server:latest \
          --amend qurtis99/http-server:latest-amd64 \
          --amend qurtis99/http-server:latest-arm64
        docker manifest push qurtis99/http-server:latest
