name: Build and Compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up C++ environment
        run: sudo apt update && sudo apt install -y build-essential automake
      - name: Configure and Build
        run: |
          autoreconf --install
          ./configure
          make
      - name: Create tarball
        run: make dist
