name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up C++ and Debian package environment
        run: |
          sudo apt update
          sudo apt install -y build-essential automake dpkg-dev debhelper

      - name: Configure and Build
        run: |
          autoreconf --install
          ./configure
          make

      - name: Create Debian package
        run: |
          dpkg-deb --build debian

      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: my_program
          path: my_program.deb
